server:
  port: 9002

spring:
  application:
    name: service-a
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.102:3306/demo?charset=utf8&convertZeroDateTime=true&useSSL=false
    username: demo
    password: 123456
    hikari:
      maxLifetime: 1765000
      idleTimeout: 10000
      minimum-idle: 6
      maximumPoolSize: 50
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

feign:
  hystrix:
    enabled: true